---
name: Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  ANSIBLE_PLAYBOOK_NAME: kubernetes

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible Requirements
        run: |
          export ANSIBLE_COLLECTIONS_PATH=$(pwd)/collections
          curl -sL https://getansible.sh/ | bash -s -- ansible-galaxy collection install -r requirements.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ANSIBLE_PLAYBOOK_NAME }}
          path: |
            **/*
            !.git*
            !LICENSE

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - id: prerelease
        run: |
          echo "prerelease=$(if [[ "${{ github.ref }}" == *"-rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Create SHA512SUMS
        run: |
          tmpdir=$(mktemp -d)
          tar -czf $tmpdir/${{ env.ANSIBLE_PLAYBOOK_NAME }}.tar.gz .
          mv $tmpdir/${{ env.ANSIBLE_PLAYBOOK_NAME }}.tar.gz .
          sha512sum ${{ env.ANSIBLE_PLAYBOOK_NAME }}.tar.gz > SHA512SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: true
          files: |
            SHA512SUMS
            ${{ env.ANSIBLE_PLAYBOOK_NAME }}.tar.gz
